on:
  push:
    branches:
      - main
  pull_request:

jobs:
  mypy:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-python@v5
      with:
        python-version: "3.13"
    - run: pip install mypy==1.8.0
    - run: mypy config.py

  tests:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-python@v5
      with:
        python-version: "3.13"
    - run: python3 tests.py
